<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit65dd49f96bdcda384df030b906ab5eee
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MediaRon\\WPPIC\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MediaRon\\WPPIC\\' => 
        array (
            0 => __DIR__ . '/../..' . '/php',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit65dd49f96bdcda384df030b906ab5eee::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit65dd49f96bdcda384df030b906ab5eee::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit65dd49f96bdcda384df030b906ab5eee::$classMap;

        }, null, ClassLoader::class);
    }
}
