<?php return array(
    'root' => array(
        'name' => 'mediaron/wp-plugin-info-card',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '4671e7b45f8ef3198615aaa3ae8ca28d7c789bb5',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'mediaron/wp-plugin-info-card' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '4671e7b45f8ef3198615aaa3ae8ca28d7c789bb5',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-stubs/wordpress-stubs' => array(
            'pretty_version' => 'v6.9.1',
            'version' => '6.9.1.0',
            'reference' => 'f12220f303e0d7c0844c0e5e957b0c3cee48d2f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-stubs/wordpress-stubs',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpstan/phpstan' => array(
            'pretty_version' => '2.2.x-dev',
            'version' => '2.2.9999999.9999999-dev',
            'reference' => '05358bafda2425ff0d07e8aba5a3619caf1865b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpstan',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'szepeviktor/phpstan-wordpress' => array(
            'pretty_version' => '2.x-dev',
            'version' => '2.9999999.9999999.9999999-dev',
            'reference' => 'aa722f037b2d034828cd6c55ebe9e5c74961927e',
            'type' => 'phpstan-extension',
            'install_path' => __DIR__ . '/../szepeviktor/phpstan-wordpress',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
    ),
);
